In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np  
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.multioutput import MultiOutputRegressor
from sklearn.gaussian_process import GaussianProcessRegressor

In [ ]:
dataset = pd.read_csv("/content/Dataset.csv", sep = ',')
dataset

Formula  n value Space Group  Layer Shift Factor (t1)  \
0       (C5H11(NH3)2(MA)Pb2I7        2         P-1                     0.14   
1                  (PEA)2PbI4        1         P-1                     0.14   
2   (C4H9NH3)2(CH3NH3)2(Pb)I4        1        Pbca                     0.49   
3     (C4H9NH3)2(CH3NH3)Pb2I7        2        Cmcm                     0.50   
4   (C4H9NH3)3(CH3NH3)2Pb3I10        3        Cmca                     0.50   
..                        ...      ...         ...                      ...   
59     (BA)2PbI4 (G-Au-P-PDs)        1        Pbca                     0.49   
60        (BA)2FAPb2I7(P-PDs)        2        Cmcm                     0.50   
61      (BA)2FAPb2I7(G-P-PDs)        2        Cmcm                     0.50   
62   (BA)2FAPb2I7(G-Au-P-PDs)        2        Cmcm                     0.50   
63          (PEA)2(MA)2Pb3I10        3          P1                     0.15   

    Layer Shift Factor (t2)  Bandgap            Cation Name Anion Name  \
0                      0.50     1.96  Phenyl Ethyl Amonium      Iodide   
1                      0.50     2.06  Phenyl Ethyl Amonium      Iodide   
2                      0.50     2.30           Butyl Ammine     Iodide   
3                      0.50     1.96           Butyl Ammine     Iodide   
4                      0.50     1.86           Butyl Ammine     Iodide   
..                      ...      ...                    ...        ...   
59                     0.50     2.30           Butyl Ammine     Iodide   
60                     0.50     1.96           Butyl Ammine     Iodide   
61                     0.50     1.96           Butyl Ammine     Iodide   
62                     0.50     1.96           Butyl Ammine     Iodide   
63                     0.46     2.06  Phenyl Ethyl Amonium      Iodide   

    Anion Size (ionic radius-pm)  Bias  Light Intensity (w/cm2)  \
0                            206   9.5             8.000000e-03   
1                            206   5.0             1.000000e-01   
2                            206   0.3             2.000000e-04   
3                            206   0.3             2.000000e-04   
4                            206   0.3             2.000000e-04   
..                           ...   ...                      ...   
59                           206   2.0             2.500000e-07   
60                           206   2.0             2.500000e-07   
61                           206   2.0             2.500000e-07   
62                           206   2.0             2.500000e-07   
63                           206   9.0             3.800000e-08   

    Light Intensity (nM)  Responsvity R (A W-1)  
0                      0                0.00387  
1                      0                0.00540  
2                      0                0.00100  
3                      0                0.01000  
4                      0                0.01000  
..                   ...                    ...  
59                     0                5.03000  
60                     0                0.16000  
61                     0               12.25000  
62                     0               18.71000  
63                     0              149.00000  

[64 rows x 13 columns]

In [ ]:
dataset['Formula'].unique()

# Import label encoder
from sklearn import preprocessing
  
label_encoder = preprocessing.LabelEncoder()
  
dataset['Formula']= label_encoder.fit_transform(dataset['Formula'])
  
dataset['Formula'].unique()

array([18, 24, 11, 15, 16, 17, 31, 12, 13, 14, 25, 29, 20,  4, 26, 22,  5,
       19, 30,  7,  2, 28,  3, 23, 27, 10,  9,  8,  6,  1,  0, 21])

In [ ]:
dataset['Space Group'].unique()


  .
label_encoder = preprocessing.LabelEncoder()
  
dataset['Space Group']= label_encoder.fit_transform(dataset['Space Group'])
  
dataset['Space Group'].unique()

array([4, 7, 3, 2, 0, 6, 1, 5])

In [ ]:
dataset['Cation Name'].unique()

label_encoder = preprocessing.LabelEncoder()
  
dataset['Cation Name']= label_encoder.fit_transform(dataset['Cation Name'])
  
dataset['Cation Name'].unique()

array([6, 1, 5, 4, 0, 3, 2])

In [ ]:
dataset['Anion Name'].unique()

dataset['Anion Name']= label_encoder.fit_transform(dataset['Anion Name'])
  
dataset['Anion Name'].unique()

array([1, 0])

In [ ]:
dataset

Formula  n value  Space Group  Layer Shift Factor (t1)  \
0        18        2            4                     0.14   
1        24        1            4                     0.14   
2        11        1            7                     0.49   
3        15        2            3                     0.50   
4        16        3            2                     0.50   
..      ...      ...          ...                      ...   
59        8        1            7                     0.49   
60        6        2            3                     0.50   
61        1        2            3                     0.50   
62        0        2            3                     0.50   
63       21        3            5                     0.15   

    Layer Shift Factor (t2)  Bandgap  Cation Name  Anion Name  \
0                      0.50     1.96            6           1   
1                      0.50     2.06            6           1   
2                      0.50     2.30            1           1   
3                      0.50     1.96            1           1   
4                      0.50     1.86            1           1   
..                      ...      ...          ...         ...   
59                     0.50     2.30            1           1   
60                     0.50     1.96            1           1   
61                     0.50     1.96            1           1   
62                     0.50     1.96            1           1   
63                     0.46     2.06            6           1   

    Anion Size (ionic radius-pm)  Bias  Light Intensity (w/cm2)  \
0                            206   9.5             8.000000e-03   
1                            206   5.0             1.000000e-01   
2                            206   0.3             2.000000e-04   
3                            206   0.3             2.000000e-04   
4                            206   0.3             2.000000e-04   
..                           ...   ...                      ...   
59                           206   2.0             2.500000e-07   
60                           206   2.0             2.500000e-07   
61                           206   2.0             2.500000e-07   
62                           206   2.0             2.500000e-07   
63                           206   9.0             3.800000e-08   

    Light Intensity (nM)  Responsvity R (A W-1)  
0                      0                0.00387  
1                      0                0.00540  
2                      0                0.00100  
3                      0                0.01000  
4                      0                0.01000  
..                   ...                    ...  
59                     0                5.03000  
60                     0                0.16000  
61                     0               12.25000  
62                     0               18.71000  
63                     0              149.00000  

[64 rows x 13 columns]

In [ ]:
#Pearson Correlation Coefficient (for identifying the most influencing material parameters). 

f, ax = plt.subplots(figsize=(65, 65), facecolor = 'white')
figure = f.get_figure()

#plotting correlation heatmap
import seaborn as sb
import matplotlib.pyplot as mp


sns.heatmap(dataset.astype(float).corr(), ax=ax, linewidth = 0.25, vmax = 1, square=True, cmap="coolwarm_r", linecolor = 'k', 
            cbar_kws={"shrink": 0.80}, annot=True, fmt='.2g', annot_kws={"size":38, "fontweight": "bold"})
ax.set_xticklabels([1,2,3,4,5,6,7,8,9,10,11,12,13,14],size = 38)
ax.set_yticklabels([1,2,3,4,5,6,7,8,9,10,11,12,13,14],size = 38)  
sns.set(font_scale = 10.0)
# displaying heatmap
mp.show()

In [ ]:
dataset.to_csv('Response.csv')

In [ ]:

from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


X = dataset[['Formula', 'n value', 'Space Group', 'Layer Shift Factor (t1)', 'Layer Shift Factor (t2)', 'Bandgap', 'Cation Name', 'Anion Name', 'Anion Size (ionic radius-pm)', 'Bias', 'Light Intensity (w/cm2)', 'Light Intensity (nM)']]
y = dataset[['Responsvity R (A W-1)']]

from sklearn.utils import shuffle
X,y = shuffle(X,y, random_state=5)


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scalerx = MinMaxScaler(feature_range = (0,1))
scalery = MinMaxScaler(feature_range = (0,1))
# training the scalar with range of data
scalerx.fit(X)
scalery.fit(y)

MinMaxScaler()

In [ ]:
# Applying transformation
scaler_X = scalerx.transform(X)
scaler_y = scalery.transform(y)

In [ ]:
# Train/test split
X_train, X_test, y_train, y_test = train_test_split(scaler_X, scaler_y, test_size=0.2, random_state=8)

In [ ]:
#dataset.dropna(axis = 0, inplace = True)
#dataset

In [ ]:
from xgboost import XGBRegressor
RegModel=XGBRegressor(
                      max_depth=500, 
                      learning_rate=0.2, 
                      n_estimators=50, 
                      booster='dart', 
                      seed = 1, 
                      )

In [ ]:
RegModel.fit(scaler_X, scaler_y)  

[08:39:45] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(booster='dart', learning_rate=0.2, max_depth=500, n_estimators=50,
             seed=1)

In [ ]:
y_xgb = RegModel.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error, mean_absolute_percentage_error
r2_score(y_test, y_xgb)

0.9998932573491004

In [ ]:
mean_absolute_error(y_test, y_xgb)

0.0003145789657830706

In [ ]:
mean_squared_error(y_test, y_xgb)

3.1109675816690193e-07

In [ ]:
y_test

array([[2.16216216e-06],
       [1.62162162e-06],
       [5.40540541e-08],
       [2.70270270e-05],
       [9.45945946e-05],
       [1.35135135e-06],
       [4.05405405e-04],
       [2.02702703e-01],
       [2.52837838e-04],
       [2.43243243e-04],
       [5.13513514e-08],
       [3.24324324e-05],
       [2.22972973e-04]])

In [ ]:
y_xgb = RegModel.predict(X_train)
r2_score(y_train, y_xgb)

0.9999739066618671

In [ ]:
mean_absolute_error(y_train, y_xgb)

0.0004896263272167905

In [ ]:
mean_squared_error(y_train, y_xgb)

5.226712591687615e-07

In [ ]:
test_df = pd.read_csv("/content/Test_X.csv")
test_df

Formula  n value  Space Group  Layer Shift Factor (t1)  \
0      11.0      1.0          7.0                     0.49   
1      15.0      2.0          3.0                     0.50   
2      17.0      4.0          3.0                     0.50   
3      18.0      1.0          7.0                     0.49   
4      19.0      2.0          2.0                     0.00   
..      ...      ...          ...                      ...   
59      NaN      NaN          NaN                      NaN   
60      NaN      NaN          NaN                      NaN   
61      NaN      NaN          NaN                      NaN   
62      NaN      NaN          NaN                      NaN   
63      NaN      NaN          NaN                      NaN   

    Layer Shift Factor (t2)  Bandgap  Cation Name  Anion Name  \
0                       0.5     2.30          1.0         1.0   
1                       0.5     1.96          1.0         1.0   
2                       0.5     1.85          1.0         1.0   
3                       0.5     2.82          1.0         0.0   
4                       0.0     2.54          1.0         0.0   
..                      ...      ...          ...         ...   
59                      NaN      NaN          NaN         NaN   
60                      NaN      NaN          NaN         NaN   
61                      NaN      NaN          NaN         NaN   
62                      NaN      NaN          NaN         NaN   
63                      NaN      NaN          NaN         NaN   

    Anion Size (ionic radius-pm)  Bias  Light Intensity (w/cm2)  \
0                          206.0   3.0                    0.049   
1                          206.0   1.0                    0.049   
2                          206.0   2.0                    0.049   
3                          196.0   3.0                    0.049   
4                          196.0   5.0                    0.049   
..                           ...   ...                      ...   
59                           NaN   NaN                      NaN   
60                           NaN   NaN                      NaN   
61                           NaN   NaN                      NaN   
62                           NaN   NaN                      NaN   
63                           NaN   NaN                      NaN   

    Light Intensity (nM)  
0                    0.0  
1                    0.0  
2                    0.0  
3                    0.0  
4                    0.0  
..                   ...  
59                   NaN  
60                   NaN  
61                   NaN  
62                   NaN  
63                   NaN  

[64 rows x 12 columns]

In [ ]:
test_df.dropna(axis = 0, inplace = True)
test_df

Formula  n value  Space Group  Layer Shift Factor (t1)  \
0     11.0      1.0          7.0                     0.49   
1     15.0      2.0          3.0                     0.50   
2     17.0      4.0          3.0                     0.50   
3     18.0      1.0          7.0                     0.49   
4     19.0      2.0          2.0                     0.00   

   Layer Shift Factor (t2)  Bandgap  Cation Name  Anion Name  \
0                      0.5     2.30          1.0         1.0   
1                      0.5     1.96          1.0         1.0   
2                      0.5     1.85          1.0         1.0   
3                      0.5     2.82          1.0         0.0   
4                      0.0     2.54          1.0         0.0   

   Anion Size (ionic radius-pm)  Bias  Light Intensity (w/cm2)  \
0                         206.0   3.0                    0.049   
1                         206.0   1.0                    0.049   
2                         206.0   2.0                    0.049   
3                         196.0   3.0                    0.049   
4                         196.0   5.0                    0.049   

   Light Intensity (nM)  
0                   0.0  
1                   0.0  
2                   0.0  
3                   0.0  
4                   0.0

In [ ]:
scalerx_test = MinMaxScaler(feature_range = (0,1))
scalery_test = MinMaxScaler(feature_range= (0,1))
#scalerx_test = MinMaxScaler()
scalerx_test.fit(test_df)
scaler_Xtest = scalerx_test.transform(test_df)

In [ ]:
predictions1_df = RegModel.predict(scaler_Xtest)

In [ ]:
predictions1_df

array([ 0.00053   ,  0.01775277,  0.0608125 , -0.00291574,  0.00027403],
      dtype=float32)

In [ ]:
test_Y_df = pd.read_csv("/content/Test_Y.csv")
test_Y_df

Responsvity R (A W-1)
0               0.000980
1               0.000580
2               0.024500
3               0.000157
4               0.024600

In [ ]:
test_Y_df.dropna(axis = 0, inplace = True)
test_Y_df

Responsvity R (A W-1)
0               0.000980
1               0.000580
2               0.024500
3               0.000157
4               0.024600

In [ ]:
scalery_test.fit(test_Y_df)
scalerY_test = scalery_test.transform(test_Y_df)

In [ ]:
scalerY_test

array([[0.03367017],
       [0.01730557],
       [0.99590885],
       [0.        ],
       [1.        ]])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error
predictions1_df 

array([ 0.00053   ,  0.01775277,  0.0608125 , -0.00291574,  0.00027403],
      dtype=float32)

In [ ]:
predictions1_df = pd.DataFrame(predictions1_df )

In [ ]:
predicted_value = scalery_test.inverse_transform(predictions1_df)
predicted_value

array([[1.6995490e-04],
       [5.9093087e-04],
       [1.6434401e-03],
       [8.5730571e-05],
       [1.6369818e-04]], dtype=float32)

In [ ]:
#scalery_test.fit(scalerY_test)
scalerY_test = scalery_test.inverse_transform(scalerY_test)

In [ ]:
scalerY_test

array([[0.00098 ],
       [0.00058 ],
       [0.0245  ],
       [0.000157],
       [0.0246  ]])

In [ ]:
mean_absolute_percentage_error(test_Y_df, predictions1_df)

10.42199865385892

In [ ]:
mean_absolute_error(test_Y_df, predictions1_df)

0.016266794573211667

In [ ]:
MSE = mean_squared_error(test_Y_df, predictions1_df)
MSE

0.00044297974467895145

In [ ]:
import math
RMSE = math.sqrt(MSE)
RMSE

0.021047083994676113